<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Create A Newsletter</title>
<link rel="stylesheet" type="text/css" href="UserSubscribes/view.css" media="all">
<script type="text/javascript" src="UserSubscribes/view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a></a></h1>
		<form id="form_1076681" class="appnitro"  method="post" action="">
					<div class="form_description">
			<h2>Create A Newsletter</h2>
			<p>To create a newsletter, please fill out the given information below. </p>
		</div>						
			<ul >
			
					<li id="li_2" >
					
					
					
		<label class="description" for="element_2">Title: </label>
		<div>
			<input id="element_2" name="element_2" class="element text medium" type="text" maxlength="300" value=""/> 
		</div> 
		</li>		<li id="li_3" >
		<label class="description" for="element_3">Description: </label>
		<div>
			<textarea id="element_3" name="element_3" class="element textarea medium"></textarea> 
		</div> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="1076681" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by GameOn!</a>
		</div>
	</div>
	<img id="bottom" src="UserSubscribes/bottom.png" alt="">
	</body>
</html>